{% set version = "8.0.20210624154013" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: a4f3044ad979dd850418fbd826257bcd6201a6a8c1f93e20402218d6adaf3814

build:
  number: 1
  skip: true  # [py2k or win]
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.12.4,<0.18|0.16.5.*
    - rdflib >=4.2.2,<=5.0.0
    - rdflib-jsonld >=0.3.0,<0.6.0
    - mistune >=0.8.1,<0.9
    - cachecontrol >=0.11.7,<0.13
    - lockfile >=0.9
    - typing_extensions

test:
  requires:
    - pytest <7
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
