{% set name = "schema-salad" %}
{% set version = "4.5.20190815125611" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4af2c0cb6e473784d42ab76068392ae0397ee3c68cb8a68fa1f4a15c8f36bd89

build:
  number: 0
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - cachecontrol >=0.11.7,<0.12  # [py<3]
    - lockfile >=0.9
    - mistune >=0.8.1,<0.9
    - rdflib >=4.2.2,<4.3.0
    - rdflib-jsonld >=0.3.0,<0.5.0  # [py<3.6]
    - requests >=1.0
    - ruamel.yaml >=0.12.4,<0.16
    - setuptools
    - six >=1.8.0
    - typing >=3.7.4  # [py!=37]
    - typing_extensions
    - future

test:
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
