{% set version = "8.3.20220801194920" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: 82f7c3bbe15351e4dbe2e2f2a8330240c5da4604f4a54f6c12ed15af0ce85917

build:
  number: 0
  skip: true  # [py2k or win]
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: SCHEMA_SALAD_USE_MYPYC=1 MYPYPATH=typeshed {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}  # for mypyc
  host:
    - python
    - pip
    - mypy >=0.910 # setup.py needs this when SCHEMA_SALAD_USE_MYPYC=1
    - types-pkg_resources
    - types-requests
    - types-dataclasses
    - ruamel.yaml >=0.17.6,<0.18|0.16.6.*
      # ruamel.yaml is needed for the type hints
      # the newer version: 0.15.99 has py.typed, which mypyc needs
    - black  # also needed for type hints
    - setuptools_scm
  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.17.6,<0.18|0.16.6.*
    - rdflib >=4.2.2,<7.0.0
    - mistune >=0.8.1,<0.9
    - cachecontrol >=0.11.7,<0.13
    - lockfile >=0.9
    - typing_extensions
    - black

test:
  requires:
    - pytest <7.2
    - pytest-xdist
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad -vv

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
