{% set version = "8.4.20231113094720" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: e6f1f5c216bc7aa446a300ea5f71c0ab19734df64ee55980c89b4ce4f5a9416a

build:
  number: 0
  skip: true  # [py2k or win]
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: SCHEMA_SALAD_USE_MYPYC=1 MYPYPATH=mypy-stubs {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # for mypyc
  host:
    - python
    - pip
    - mypy ==1.7.0 # setup.py needs this when SCHEMA_SALAD_USE_MYPYC=1
    - types-pkg_resources
    - types-requests
    - types-dataclasses
    - types-setuptools
    - ruamel.yaml >=0.17.6,<0.19
      # ruamel.yaml is needed for the type hints
      # the newer version: 0.15.99 has py.typed, which mypyc needs
    - black >=19.10b0 # also needed for type hints
    - rdflib >=4.2.2,<8.0.0  # more type hints
    - setuptools_scm >=8.0.4,<9
    - importlib_resources >=1.4
  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.17.6,<0.19
    - rdflib >=4.2.2,<8.0.0
    - mistune >=2.0.3,<2.1
    - cachecontrol >=0.13,<0.14
    - filelock
    - black
    - importlib_resources >=1.4

test:
  requires:
    - pytest <7.5
    - pytest-xdist
    - setuptools
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad -vv  # [ not aarch64 ]

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
