{% set version = "8.1.20210627200047" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: e2f4d6eadb060f3d88372bb4bdefb7c22eb4b191c2657a8a82183d100148fac5

build:
  number: 0
  skip: true  # [py2k or win]
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: SCHEMA_SALAD_USE_MYPYC=1 MYPYPATH=typeshed {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - mypy
    - {{ compiler('c') }}  # for mypyc
    - types-pkg_resources
    - types-requests
    - ruamel.yaml >=0.15.99,<0.18|0.16.5.*
      # ruamel.yaml 0.15.99 has py.typed, which mypyc needs
  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.12.4,<0.18|0.16.5.*
    - rdflib >=4.2.2,<=5.0.0
    - rdflib-jsonld >=0.3.0,<0.6.0
    - mistune >=0.8.1,<0.9
    - cachecontrol >=0.11.7,<0.13
    - lockfile >=0.9
    - typing_extensions

test:
  requires:
    - pytest <7
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
