{% set version = "7.1.20210309094900" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: 2593129052324bb1406c039d36e84ed01447d610748193bbe8de4d61ff4d9d97
  patches:
    # Workaround for https://github.com/pytest-dev/pytest/issues/6489
    - 0001-Workaround-for-pytest-realpath-issue-on-Python-3.8-and-Windows.patch

build:
  noarch: python
  number: 0
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools
    - requests >=1.0
    # Avoid ruamel.yaml >=0.16,<0.16.5 due to builds with broken dependency.
    # ref: https://github.com/conda-forge/ruamel.yaml-feedstock/pull/117
    - ruamel.yaml >=0.12.4,<0.16|0.16.5.*
    - rdflib >=4.2.2,<4.3.0
    - rdflib-jsonld >=0.3.0,<0.6.0
    - mistune >=0.8.1,<0.9
    - cachecontrol >=0.11.7,<0.12
    - lockfile >=0.9
    - typing_extensions

test:
  requires:
    - pytest <5
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
