{% set version = "8.2.20220204150214" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: 3e53dbfe7137796b9e5135920e96bb2713ded9e7be2859dae554d1dc8b029704

build:
  number: 0
  skip: true  # [py2k or win]
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: SCHEMA_SALAD_USE_MYPYC=1 MYPYPATH=typeshed {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}  # for mypyc
  host:
    - python
    - pip
    - mypy >=0.910 # setup.py needs this when SCHEMA_SALAD_USE_MYPYC=1
    - types-pkg_resources
    - types-requests
    - ruamel.yaml >=0.15.99,<0.18|0.16.6.*
      # ruamel.yaml is needed for the type hints
      # the newer version: 0.15.99 has py.typed, which mypyc needs
    - black  # also needed for type hints
  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.12.4,<0.18|0.16.6.*
    - rdflib >=4.2.2,<6.0.0  # [py<37]
    - rdflib-jsonld >=0.3.0,<=0.6.1  # [py<37]
    - rdflib >=4.2.2,<7.0.0  # [py>=37]
    - mistune >=0.8.1,<0.9
    - cachecontrol >=0.11.7,<0.13
    - lockfile >=0.9
    - typing_extensions
    - black

test:
  requires:
    - pytest <7
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
