{% set version = "8.5.20240410123758" %}

package:
  name: schema-salad
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/schema-salad/schema-salad-{{ version }}.tar.gz
  sha256: 36da8097ece4cc327d5e1151179efb189043d7cd8d5ce282f5b369ad17647d7b

build:
  number: 1
  skip: true  # [py2k or win]
  entry_points:
    - schema-salad-tool=schema_salad.main:main
    - schema-salad-doc=schema_salad.makedoc:main
  script: SCHEMA_SALAD_USE_MYPYC=1 MYPYPATH=mypy-stubs {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}  # for mypyc
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - mypy ==1.9.0 # setup.py needs this when SCHEMA_SALAD_USE_MYPYC=1
    - types-pkg_resources
    - types-requests
    - types-dataclasses
    - types-setuptools
    - ruamel.yaml >=0.17.6,<0.19
      # ruamel.yaml is needed for the type hints
      # the newer version: 0.15.99 has py.typed, which mypyc needs
    - black >=24 # also needed for type hints
    - rdflib >=4.2.2,<8.0.0  # more type hints
    - setuptools_scm >=8.0.4,<9
    - importlib_resources >=1.4  # [py<39]
  run:
    - python
    - setuptools
    - requests >=1.0
    - ruamel.yaml >=0.17.6,<0.19
    - rdflib >=4.2.2,<8.0.0
    - mistune >=3,<3.1
    - cachecontrol >=0.13,<0.15
    - filelock
    - black
    - importlib_resources >=1.4  # [py<39]

test:
  requires:
    - pytest <9
    - pytest-xdist
    - setuptools
  imports:
    - schema_salad
    - schema_salad.tests
  commands:
    - schema-salad-tool --help
    - schema-salad-doc --help
    - python -m pytest --pyargs schema_salad -vv  # [ not aarch64 ]

about:
  home: https://schema-salad.readthedocs.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)
  dev_url: https://github.com/common-workflow-language/schema_salad

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
