context:
  version: "8.10.20260825112551"

package:
  name: schema-salad
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/s/schema-salad/schema_salad-${{ version }}.tar.gz
  sha256: 426af8bae86b1b8026469968bcd0802e6c61fd6c44c6b1f77d48467164a6ac74

build:
  number: 1
  skip: win
  python:
    entry_points:
      - schema-salad-tool = schema_salad.main:main
      - schema-salad-doc = schema_salad.makedoc:main
  script:
    env:
      SCHEMA_SALAD_USE_MYPYC: "1"
      MYPYPATH: mypy-stubs
    content: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}  # for mypyc
    - ${{ stdlib('c') }}
    - mypy ==2.3.1
  host:
    - python
    - pip
    - mypy ==2.3.1 # setup.py needs this when SCHEMA_SALAD_USE_MYPYC=1
    - types-requests
    - types-dataclasses
    - types-setuptools
    # ruamel.yaml is needed for the type hints
    # the newer version: 0.15.99 has py.typed, which mypyc needs
    - ruamel.yaml >=0.17.6,<0.20
    - black >=24  # also needed for type hints
    - rdflib >=4.2.2,<8.0.0  # more type hints
    - setuptools_scm >=8.0.4,<11
    - filelock  # needed for type hints
    - setuptools >=50  # build backend
    - cachecontrol-with-filecache >=0.14.0,<0.15  # needed for type hints
    - rich-argparse
    - mistune >=3.3.0,<3.4
  run:
    - python
    - requests >=1.0
    - ruamel.yaml >=0.17.6,<0.20
    - rdflib >=4.2.2,<8.0.0
    - mistune >=3.3.0,<3.4
    - cachecontrol-with-filecache >=0.14.0,<0.15
    - mypy_extensions
    - filelock
    - rich-argparse
    - black

tests:
  - python:
      imports:
        - schema_salad
        - schema_salad.tests
      pip_check: true
  - script:
      - schema-salad-tool --help
      - schema-salad-doc --help
      # the emulated aarch64 runners are too slow for the full test suite
      - if: target_platform != "linux-aarch64"
        then: python -m pytest --pyargs schema_salad -vv -n auto
    requirements:
      run:
        - pytest <9.1
        - pytest-xdist
        - setuptools

about:
  homepage: https://schema-salad.readthedocs.io/
  repository: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Schema Annotations for Linked Avro Data (SALAD)

extra:
  recipe-maintainers:
    - croth1
    - chapmanb
    - pvanheus
    - mr-c
